---
- hosts: raspberry 

  gather_facts: no
  tasks:

#This checks to see if the apache page is present

  - action: uri url=http://raspberrypi return_content=yes
    register: webpage

  - fail: msg='service is not happy'
    when: "'It works!' not in webpage.content"
